### ISSUE TITLE
more lenient joins

### ISSUE THREAD

**Issue by shabbybanks** [wmurphyrd/fiftystater#5]
Cool package, will be very helpful.
Without looking at the `crimes` data in the example in the `README`, I had no way of knowing whether the map joined on state name abbreviations or state names. Perhaps a more robust form would allow for state names, state abbreviations, and not care about upper/lower case.

**Comment by wmurphyrd** [comment]
Please see `?fifty_states` for descriptions of the fields including how the state name format. If you need to join by a different format, the `state.abb` and `state.name` data provided in base R can be handy:

```
dplyr::inner_join(
  fifty_states,
  data.frame(name = tolower(state.name), abb = state.abb),
  by = c(id = "name")
)
