### ISSUE TITLE
Drawing border lines 

### ISSUE THREAD

**Issue by aja2182** [wmurphyrd/fiftystater#8]
Thanks for this package. It's super easy to use (to include Hawaii and Alaska). One issue I'm running into is how to specify the color between states. Usually I just add geom_polygon(color = "grey90", size = 0.2), but not sure how to do that in this case.

**Comment by wmurphyrd** [comment]
I believe you set the color aesthetic on geom_map to draw border lines

**Comment by aja2182** [comment]
Amazing it worked thanks so much Will :)
